generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Member
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          member
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing   #setting the css to a placeholder

    config:
      actions: ~
      fields:
          name:
              label:       '姓名'
          phone:
              label:       '電話'
          sex:
              label:       '性別'
          created_at:
              label:       '報名時間'
          updated_at:
              label:       '更新時間'
      list:
          title:           '報名列表'
          display:         [id,name,email,phone,_sex,created_at,updated_at]
      filter:
          display:         [name,email,phone,created_at,updated_at]
      form:    ~
      edit:
          title:           '編輯報名資料'
      new:
          title:           '新增報名資料'
