<?php

/**
 * SpeakerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpeakerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpeakerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Speaker');
    }
}