all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=xxx'
      username: root
      password: xxxx
      attributes:
        default_table_collate: utf8_general_ci
        default_table_charset: utf8